
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:




    

        - task: Maven@3
          inputs:
            mavenPomFile: 'UC3.parent/pom.xml'
            goals: 'package build'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false